name = "GaussianProcesses"
uuid = "891a1506-143c-57d2-908e-e1f8e92e6de9"
license = "MIT"
version = "0.11.1"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
ElasticPDMats = "2904ab23-551e-5aed-883f-487f97af5226"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
ScikitLearnBase = "6e75b9c4-186b-50bd-896f-2d2496a4843e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Distances = "0.7, 0.8"
Distributions = "0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22"
Documenter = "0.24"
ElasticArrays = "0.2, 0.3, 0.4, 1.0"
ElasticPDMats = "0.2"
FastGaussQuadrature = "0.3, 0.4"
ForwardDiff = "0.10"
Optim = "0.19, 0.20"
PDMats = "0.9"
ProgressMeter = "1.2"
RecipesBase = "0.6, 0.7, 0.8"
ScikitLearnBase = "0.4, 0.5"
SpecialFunctions = "0.7, 0.8, 0.9, 0.10"
StaticArrays = "0.6, 0.9, 0.12"
StatsFuns = "0.7, 0.8, 0.9"
Zygote = "0.3, 0.4"
julia = "1"

[extras]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Calculus", "Distributions", "Test"]
